
import _create_mnemonic_wallet from './commands/create-mnemonic-wallet';
import _decrypt from './commands/decrypt';
import _delegate from './commands/delegate';
import _encrypt from './commands/encrypt';
import _get_balances from './commands/get-balances';
import _get_cosmos_balance from './commands/get-cosmos-balance';
import _get_latest_block from './commands/get-latest-block';
import _get_pool_apr from './commands/get-pool-apr';
import _get_price from './commands/get-price';
import _get_staking_rewards from './commands/get-staking-rewards';
import _get_transaction from './commands/get-transaction';
import _ibc_transfer from './commands/ibc-transfer';
import _ibc_wip from './commands/ibc-wip';
import _join_pool from './commands/join-pool';
import _join from './commands/join';
import _list_apis from './commands/list-apis';
import _list_pools from './commands/list-pools';
import _list_prices from './commands/list-prices';
import _load_recipe from './commands/load-recipe';
import _lock_tokens from './commands/lock-tokens';
import _lock from './commands/lock';
import _reinvest_copy from './commands/reinvest-copy';
import _reinvest from './commands/reinvest';
import _salt_decrypt from './commands/salt-decrypt';
import _salt_encrypt from './commands/salt-encrypt';
import _salt_generate from './commands/salt-generate';
import _send from './commands/send';
import _shamir_decrypt from './commands/shamir-decrypt';
import _shamir_encrypt from './commands/shamir-encrypt';
import _swap_exact_amount_in from './commands/swap-exact-amount-in';
import _swap from './commands/swap';
import _wallet_from_mnemonic from './commands/wallet-from-mnemonic';
const Commands = {};
Commands['create-mnemonic-wallet'] = _create_mnemonic_wallet;
Commands['decrypt'] = _decrypt;
Commands['delegate'] = _delegate;
Commands['encrypt'] = _encrypt;
Commands['get-balances'] = _get_balances;
Commands['get-cosmos-balance'] = _get_cosmos_balance;
Commands['get-latest-block'] = _get_latest_block;
Commands['get-pool-apr'] = _get_pool_apr;
Commands['get-price'] = _get_price;
Commands['get-staking-rewards'] = _get_staking_rewards;
Commands['get-transaction'] = _get_transaction;
Commands['ibc-transfer'] = _ibc_transfer;
Commands['ibc-wip'] = _ibc_wip;
Commands['join-pool'] = _join_pool;
Commands['join'] = _join;
Commands['list-apis'] = _list_apis;
Commands['list-pools'] = _list_pools;
Commands['list-prices'] = _list_prices;
Commands['load-recipe'] = _load_recipe;
Commands['lock-tokens'] = _lock_tokens;
Commands['lock'] = _lock;
Commands['reinvest-copy'] = _reinvest_copy;
Commands['reinvest'] = _reinvest;
Commands['salt-decrypt'] = _salt_decrypt;
Commands['salt-encrypt'] = _salt_encrypt;
Commands['salt-generate'] = _salt_generate;
Commands['send'] = _send;
Commands['shamir-decrypt'] = _shamir_decrypt;
Commands['shamir-encrypt'] = _shamir_encrypt;
Commands['swap-exact-amount-in'] = _swap_exact_amount_in;
Commands['swap'] = _swap;
Commands['wallet-from-mnemonic'] = _wallet_from_mnemonic;

  export { Commands }; 

  